# Generated by Django 5.0.3 on 2025-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidate_city_candidate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
